name: core
description: A new Flutter package project.
version: 0.0.1
homepage:

publish_to: none

environment:
    sdk: ">=2.16.2 <3.0.0"
    flutter: ">=1.17.0"

dependencies:
    flutter:
        sdk: flutter

    movie:
        path: ../movie
    tv_show:
        path: ../tv_show

    firebase_core: ^1.17.0
    firebase_crashlytics: ^2.8.0
    google_fonts: ^2.3.2
    equatable: ^2.0.3
    http: ^0.13.4
    flutter_bloc: ^8.0.1
    cached_network_image: ^3.2.0
    flutter_svg: ^1.0.3

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^1.0.0

flutter:
